### ISSUE TITLE
Not seeing this when I run your code

### ISSUE THREAD

**Issue by TheByteSizeDev** [JeremyWhiteDev/daily-journal#11]
😢 Not sure why but I'm not seeing your form when I run your code!

https://github.com/JeremyWhiteDev/daily-journal/blob/879f7d46cd1f8c0f7c13581ebf66f8adbf0989c8/scripts/form.js#L4-L35

**Comment by JeremyWhiteDev** [comment]
After testing this code, I'm not sure why the form isn't displaying for you. I repulled this branch down and everything still functions as expected. Form still shows. Admittedly I didn't see the form or content right away when testing this because I forgot to start running json-server on port 8000. Let me know if there's anything fishy you see in dev tools if you take another look at this.

**Comment by TheByteSizeDev** [comment]
Oh my bad I see now. You have your database running on `8000` while I have mine on `8088`. Whoops!
